package com.attestorforensics.mobifumecore.controller.util;

public enum ItemErrorType {
  FILTER_OUTOFTIME,
  FILTER_TIMESATURATION,
  FILTER_TIME,
  HUMIDIFIER_WATER,
  BASE_LATCH,
  BASE_HEATER,
  BASE_TEMPERATURE,
  BASE_HUMIDITY,
  DEVICE_CONNECTION_LOST,
  FILTER_SATURATION
}
